### ISSUE TITLE
Pass ChildContent to Modal

### ISSUE THREAD

**Issue by jens-cailliau** [blazority/support#111]
**Feature Type**
[ ] Clarity Port
[ x ] Enhancement

**Description**
I'm currently working on a ModalService.

As explained in:
[https://github.com/blazority/support/issues/59](https://github.com/blazority/support/issues/59)

The idea was that a user can also pass it's blazor component.

![image](https://user-images.githubusercontent.com/16465655/196673480-720842cd-61f4-456a-a2cc-f04bf8064465.png)

Then the blazor component could like this :
![image](https://user-images.githubusercontent.com/16465655/196673638-6d1d0e3d-172f-4085-925d-3ff1e3c21709.png)

Unfortunately this isn't working, I think it's because inside the modal there is no <ChildContent> tag.
Can you have a look?

**Comment by karan-kang** [comment]
@pufpufpuf I am not sure what you mean modal does not have a tag. 
Do you mean the body is empty? May be a screenshot of the modal dialog and the DOM tree (from dev tools) will help.

**Comment by pufpufpuf** [comment]
Hey @karan-kang, I meant there is no tag ChildContent in the modal.

As seen on my screenshots, in my ModalService, I have the <Modal> tag.
Only allowed tags that are allowed are ModalTitle, ModalBody, ModalFooter.

I wanted to add the title, body & footer from a component and that doesn't seem to work unfortunately.

**Comment by karan-kang** [comment]
@jens-cailliau  thanks, I should be able to add this

**Comment by karan-kang** [comment]
Due to the way the underlying control works, it is not possible to replace the RenderFragements of ModalTitle/ModalBody/ModalFooter with ModalContent, as it it breaks styling and other modal functionality.

If you want to achieve through this service, it would be best to populate the supported RenderFragement as well.
Closing this as no action on Blazority is needed at the moment.
